### ISSUE TITLE
Checking if a vault was initialized doesn't always hold

### ISSUE THREAD

**Issue by cleanunicorn** [fiatdao/fiat#8]
**Description**

An authorized account can call `init` to initialize a new vault.

https://github.com/fiatdao/fiat/blob/50c73cab022d12cb233da51c98af8d7554a9e547/src/Publican.sol#L62-L65

During initialization, a check is performed to make sure the same vault was not already initialized previously.

https://github.com/fiatdao/fiat/blob/50c73cab022d12cb233da51c98af8d7554a9e547/src/Publican.sol#L67

The check is done by making sure `interestPerSecond != 0`.

Once the check passes, this property is set as `WAD`.

https://github.com/fiatdao/fiat/blob/50c73cab022d12cb233da51c98af8d7554a9e547/src/Publican.sol#L68

A second call to the same `init` method would fail because the `interestPerSecond` vault property differs from zero.

However, the `interestPerSecond` can be overwritten by an authorized account by calling `setParam`:

https://github.com/fiatdao/fiat/blob/50c73cab022d12cb233da51c98af8d7554a9e547/src/Publican.sol#L73-L84

This time, the authorized account can set any value, even the `0` value.

If the authorized account sets the `0` value, the check that makes sure a vault was already initialized is not valid anymore.

Consider these steps:

- `Publican.init(0xVAULT)`
- `Publican.setParam(0xVAULT, "interestPerSecond", 0)
- `Publican.init(0xVAULT)` - will not fail and will initialize the same vault twice

**Recommendation**

If a `0` value is considered invalid, `setParam` should not allow setting the `interestPerSecond` to `0`.

However, if the `interestPerSecond` can be set to `0` and it is a valid value, consider adding a flag that marks if a vault was already initialized.

**Comment by SolcAndMe** [comment]
The DAO ultimately has power over the protocol. There are no harmful side effects to this.
